### ISSUE TITLE
CSS color decorators and JS autocomplete problem

### ISSUE THREAD

**Issue by Reedo0910** [ecmel/vscode-html-css#1]
Thank you!!! Your extension really helps me a lot. It works great! And I have a few questions to ask.
1. I notice that the CSS color decorators attached to color values inside style tags in html files seem not working in vscode 1.3. 
![800e1a0452d3d1c214b39616bc17b4d6_b](https://cloud.githubusercontent.com/assets/19267441/16905371/95122392-4cd7-11e6-884a-7751ddbdefd0.png)
May your extension help fix this problem in future updates?
2. If there is any possibility to fix the JS autocomplete problem inside script tags in html files?
Thanks again.

**Comment by ecmel** [comment]
Thank you.

1. There is support for color decorators in https://github.com/Microsoft/vscode-css-languageservice, but I am not sure how to integrate it with the extension yet.

2. Java Script support is not yet extracted to its own module yet. If such a module is extracted, it will be very easy to support JS as well.

**Comment by Reedo0910** [comment]
Thanks.

**Comment by ecmel** [comment]
This can be soon fixed by https://github.com/Microsoft/vscode/issues/8938 both for css and js.

**Comment by Reedo0910** [comment]
Good news! Thank you.
