### ISSUE TITLE
add .vue file support

### ISSUE THREAD

**Issue by beeplin** [ecmel/vscode-html-css#11]
.vue files can be simply treated as .html. please~ :)

**Comment by ecmel** [comment]
Already seems to work with .vue files. Added a test file.

Which version of VS Code are you using?

**Comment by beeplin** [comment]
yes if you associate vue files to HTML type, it works. but if you use 'vue component' plugin and associate vue files to vue component type, it doesn't work. 

this vue component plugin provides some vital feathers like coffeescript/less/stylus/jade detection and recognition. 

i am using latest VScode 1.6.1, with `vue component` plugin 0.4.0

**Comment by ecmel** [comment]
Are you using https://marketplace.visualstudio.com/items?itemName=seanwash.vue ?

**Comment by beeplin** [comment]
yes


来自 魅族 PRO 6

-------- 原始邮件 --------
发件人：Ecmel Ercan <notifications@github.com>
时间：周一 10月17日 23:01
收件人：ecmel/vscode-html-css <vscode-html-css@noreply.github.com>
抄送：Beep LIN <beeplin@gmail.com>,Author <author@noreply.github.com>
主题：Re: [ecmel/vscode-html-css] add .vue file support (#11)

**Comment by ecmel** [comment]
https://github.com/ecmel/vscode-html-css/commit/0220878af85a47423242def7319179c1d6f05551 should fix.
