### ISSUE TITLE
Please add Svelte support.

### ISSUE THREAD

**Issue by skdigital** [ecmel/vscode-html-css#123]
Hi,

Please add support for .Svelte files, its an awesome new framework/javascript compiler that is gaining traction.

Svelte is a new frontend javascript framework that is developing nicely, it just hit version 3. Its actually a javascript compiler that can ship a full webapps code as small as preact (around 3kb) after compilation. There is also a nice framework built around svelte called Sapper that is very similar to reacts Nextjs. Svelts's Sapper runs much faster and smaller than Next.js, and has a few very interesting nice to have features that make developing with it very nice.

Trust me, Svelte and Sapper are going to do very well. It's basically the birth child between Vuejs and Reacts with much better speed and bundle sizes.

Hope this helps.

Here are the links to the respective framework pages.
Svelte: https://svelte.dev
Sapper: https://sapper.svelte.dev/

Bests,

SKDigital.

**Comment by soullivaneuh** [comment]
I agree for the support. Plus, svelte file are basically just `html`, `css` and `javascript` blocks onto one file.

It should not be so hard to adapt the extension IMHO.

**Comment by soullivaneuh** [comment]
I found this: https://github.com/ecmel/vscode-html-css/blob/247b9d5478c7f8b7f9718de90fa46fdce1f38d20/src/extension.ts#L178-L198

Why not make it configurable? :thinking:

**Comment by soullivaneuh** [comment]
@skdigital Please see #142
