### ISSUE TITLE
Please add support for smarty .tpl files

### ISSUE THREAD

**Issue by SharakPL** [ecmel/vscode-html-css#126]
Right now it only suggests css/scss classes if .tpl files are associated with html language mode. With smarty enabled by [this extension](https://marketplace.visualstudio.com/items?itemName=imperez.smarty) I get proper syntax highlighting and some snippets, but lose css class suggestions :(

**Comment by SharakPL** [comment]
@ecmel Is this as simple as updating lang constant in this file and compiling?
https://github.com/ecmel/vscode-html-css/blob/7ebfc6a60583368842327ff815e767c31f0304fe/src/extension.ts#L178-L197

**Comment by agiannis** [comment]
Why is this closed? There is no support for smarty yet. If you set file associations as html, you will loose the smarty syntax and formatting.

**Comment by SharakPL** [comment]
@ecmel will you add smarty support?
