### ISSUE TITLE
Sass/scss support

### ISSUE THREAD

**Issue by congrady** [ecmel/vscode-html-css#13]
Hello,

I'm using Vue.js 2 together with scss.
I'd like to have scss instead of css intellisense(suggestion, errors) inside my <style lang="scss"> tags.
(Or just globally in all style tags).

Is it already possible somehow? An if not, can you please add a support for this?

Many thanks!

**Comment by ecmel** [comment]
Hi, `<style>` tag support is provided by vscode itself, please check  https://github.com/ecmel/vscode-html-css/issues/9

**Comment by ecmel** [comment]
There is an upstream issue as well: https://github.com/seanwash/vscode-vue-components/issues/4

**Comment by ecmel** [comment]
Style tag support is provided by upstream, https://github.com/ecmel/vscode-html-css/issues/9
