### ISSUE TITLE
 Suggestions come out everywhere

### ISSUE THREAD

**Issue by phibersoft** [ecmel/vscode-html-css#138]
No matter where I hit the spot, suggestions come out. Is it my fault? Anyway thank you very much.

Like this : 
https://ibb.co/CwNDcZ2

**Comment by dlucian85** [comment]
I'm also searching for a fix, or maybe the author can add a setting to specify which type of files this extension to be enabled in.

**Comment by dlucian85** [comment]
I was looking for the same option but looks like oficially there is no way of solving this issue, but i came of with a quick fix.
Just go to `C:\` >  `Users` > yourWindowsUser > `.vscode` > `extensions` > `ecmel.vscode-html-css-0.2.3` > `dist` and open `extension.js` file. You will see a minified version of the extension but just search for `const t=["html","django-html","laravel-blade` and remove your desired language from the array. Save it and reload VS Code. This worked for me. Hope this helps :)

**Comment by ivanvoznyakovsky** [comment]
I do thank author for the work but this needs a fix asap. it is very irritating to get this kind of dropdown in typescript files
![image](https://user-images.githubusercontent.com/6418145/64283123-7bf4e300-cf5f-11e9-91e3-ec76cb8b3d9e.png)

**Comment by Zonciu** [comment]
After binary enabling/disabling my extensions, I finally found the problem why css suggestion come out everywhere......
So here I am......

**Comment by Zonciu** [comment]
I rolled it back to 0.2.0.

**Comment by CapLonelyFlaw** [comment]
I rolled back too, but now, I can't see suggestions inside class attribute.

**Comment by papiliond** [comment]
+

**Comment by garyking** [comment]
More specifically, when type a period anywhere, then the CSS classes IntelliSense dropdown will appear.

**Comment by gvmohzibat** [comment]
+1

**Comment by rushvora** [comment]
> I was looking for the same option but looks like oficially there is no way of solving this issue, but i came of with a quick fix.
> Just go to `C:\` > `Users` > yourWindowsUser > `.vscode` > `extensions` > `ecmel.vscode-html-css-0.2.3` > `dist` and open `extension.js` file. You will see a minified version of the extension but just search for `const t=["html","django-html","laravel-blade` and remove your desired language from the array. Save it and reload VS Code. This worked for me. Hope this helps :)

This fix works great for me, thank you so much!

**Comment by Martinspire** [comment]
So why is this still a thing? Why isn't there a setting yet to override this?

**Comment by mctrafik** [comment]
Just found this out. Had to remove the extension because of it. :(

**Comment by nick-lvov-dev** [comment]
> I was looking for the same option but looks like oficially there is no way of solving this issue, but i came of with a quick fix.
> Just go to `C:\` > `Users` > yourWindowsUser > `.vscode` > `extensions` > `ecmel.vscode-html-css-0.2.3` > `dist` and open `extension.js` file. You will see a minified version of the extension but just search for `const t=["html","django-html","laravel-blade` and remove your desired language from the array. Save it and reload VS Code. This worked for me. Hope this helps :)

Worked great, I've reacted with every positive emote I could so everyone would be able to see this reply! This issue was so annoying, thanks a lot for the solution!

**Comment by Zonciu** [comment]
Looks like they doesn't plan to fix this bug……now I use `IntelliSense for CSS class names in HTML`
