### ISSUE TITLE
Need support for HTML (EEx)

### ISSUE THREAD

**Issue by reducio** [ecmel/vscode-html-css#139]
Thanks you so much for extension and good experience!

Add support for [HTML (EEx)](https://hexdocs.pm/eex/EEx.html), please.
In particular, it will help developers who work with Tailwind CSS in HTML (EEx).

[Topic 1](https://elixirforum.com/t/how-to-force-the-tailwind-css-intellisense-extension-for-vscode-work-with-html-eex-and-html-leex-files/25520)

**Comment by dvic** [comment]
@ecmel any chance to do a release soon? It would make life a lot easier for Elixir users :) In any case, thanks for the lib 👍

**Comment by sabit990928** [comment]
Hey @ecmel. Can you give a hint how to make an extension work with phoenix files? Seems like few things changed since that PR merged. That's what I put into my settings file:

```json
  "css.enabledLanguages": [
    "HTML (EEx)"
  ],
  "css.styleSheets": [
    "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
  ]
```

What I want is to add class recommendations for bootstrap 5 in `.heex` and inline `.ex` files. Thanks

**Comment by ecmel** [comment]
Hi, what is the language id for .hhex and .ex files?

**Comment by sabit990928** [comment]
I think it's a `phoenix-heex` and `elixir`, @ecmel.
