### ISSUE TITLE
Doesn't work with blade extension

### ISSUE THREAD

**Issue by TheColorRed** [ecmel/vscode-html-css#14]
There are multiple blade extensions, and I have the following blade extension installed:

https://marketplace.visualstudio.com/items?itemName=onecentlin.laravel-blade

This doesn't work with that extension, could you please add support for it?

github: https://github.com/onecentlin/laravel-blade-snippets-vscode

**Comment by ecmel** [comment]
Commit 3dd6d95e7ffb8982fa63dcf38ccb549b1b62e9f8 should fix.
