### ISSUE TITLE
The extension causes wrong Intellisense

### ISSUE THREAD

**Issue by hua03** [ecmel/vscode-html-css#146]
The CSS class in the project will be displayed when the Intellisense is displayed

![](https://raw.githubusercontent.com/hua03/image-gallery/master/img/20200113100800.png)

![](https://raw.githubusercontent.com/hua03/image-gallery/master/img/20200113101111.png)

**Comment by Smrman** [comment]
I have about the same issue on my side as well.

The project i'im working on is **100% in TypeScript**.
I **don't have any CSS file** in my project, nor HTML.

However, when this extension is enabled, IntelliSense always add those propreties completions to the current object, which are wrong and don't make any sense.

![image](https://user-images.githubusercontent.com/17651422/85228622-a4fa3d80-b3e4-11ea-975e-f6a0842eb309.png)

The propreties added are always the same ("code", "config", "edit", "go", "result", and "results").
It shows all these propreties come from an "index.css" file, which doesn't exist in my project.
