### ISSUE TITLE
I need to have a space character before the cursor for the list of options to appear

### ISSUE THREAD

**Issue by thiagomota456** [ecmel/vscode-html-css#148]
If I type 'class="nameClass ..." ' a list of options is not displayed. But if I type 'class=" nameClass ..." ' (with a space before the class name), the extension shows the list of classes in css.

I believe it is necessary to add a directive to not consider ' " ' as part of the string.

**Comment by phibershinigami** [comment]
Hi thia,
Im using ctrl + space for this.
Maybe its help
