### ISSUE TITLE
Add support for Handlebars

### ISSUE THREAD

**Issue by AurelioDeRosa** [ecmel/vscode-html-css#15]
It'd be nice if you could support Handlebars files.

**Comment by ecmel** [comment]
Which handlebars plugin are you using?

**Comment by AurelioDeRosa** [comment]
None in particular, HBS can be used without plugins.

**Comment by ecmel** [comment]
Should be fixed with https://github.com/ecmel/vscode-html-css/commit/7d866f9af273fcd84e00c9e44c319a6db601454e
