### ISSUE TITLE
Support for Automatic remote css files

### ISSUE THREAD

**Issue by yCodeTech** [ecmel/vscode-html-css#152]
It is a bit tedious to add every remote css file in the settings. 

It would be nice for the extension to do this automatically for all files linked as a href stylesheet.  Enabling this could be controlled by a VSCode setting.

**Comment by MS00-GitIt** [comment]
@yCodeTech How do I use remote css after I add the link to the settings?

**Comment by yCodeTech** [comment]
Start typing the class name, and the list should come up on the auto completion menu as you type or by pressing `CTRL+ SPACE`
