### ISSUE TITLE
Does this support HTML mixed with PHP code?

### ISSUE THREAD

**Issue by Soft-Shock** [ecmel/vscode-html-css#16]
I am trying to use the extension with .php files that have html code mixed in, no auto complete is coming up. I renamed the files to .html (just to test), and none of the completion is showing up (it has some <?php tags in it).

I waited a long time for css definitions to load, still not working.

Is there a reason the .php files and .html files with php in them are not auto-completing the classes or ids?

**Comment by ecmel** [comment]
Hi, which PHP plugin are you using?

Extension currently supports laravel-blade plugin

**Comment by Soft-Shock** [comment]
I see, I am not using laravel-blade (*.blade.php files). Actually I am modifying some WordPress Views (known as Templates in WordPress).

Other PHP Plugins I am using are PHP Debug, PHP Intellisense, PHP Symbols.

I am curious, why doesn't the completion work on just the html part of the .php file? Why can't the plugin recognize the html tags and assist with the css completion? Do the `<?php` tags just cause the scanning of the document to stop? Or is it as simple as allowing your HTML parser to run on .php files?

**Comment by ecmel** [comment]
Commit https://github.com/ecmel/vscode-html-css/commit/e9e4bb1b4c692cd55e29d7a5fa820a22f0f0c74a should fix.

**Comment by Soft-Shock** [comment]
Thank you! I appreciate your time.
