### ISSUE TITLE
Support for .jade and .pug files

### ISSUE THREAD

**Issue by petsto** [ecmel/vscode-html-css#17]
He there!
I was wondering if there's a way to add .pug files class names autocompletion.
The extension works perfectly in a pure HTML file, but would be awesome if it can support and pugjs. Is there a way I can manually set it up to also include the functionality in other files than just .html.

Thanks!
Keep up the awesome work!

**Comment by aminchoroomi** [comment]
And also support for `.vash` files. It would be even better to configure extensions in `resource.json` file.

Thanks anyway for the great extension

**Comment by ecmel** [comment]
Should be fixed with https://github.com/ecmel/vscode-html-css/commit/7d866f9af273fcd84e00c9e44c319a6db601454e
