### ISSUE TITLE
Support completion from workspace CSS file(s)

### ISSUE THREAD

**Issue by timurmelnikov** [ecmel/vscode-html-css#181]
HTML class autocompletion not working after upgrading to 0.9.7

**Comment by ecmel** [comment]
Are you trying to complete from local css files?

**Comment by onipilot** [comment]
So the new version is dropping support for local css files?

**Comment by ecmel** [comment]
Working on local css files support.

**Comment by timurmelnikov** [comment]
So far I returned to version 0.2.3...

**Comment by jasonchuot07** [comment]
> So far I returned to version 0.2.3...

Can you help me with my workspace ? I returned to 0.2.3 but the suggestions still didn't show up

**Comment by ecmel** [comment]
@jasonchuot07  Could you please tell us your settings? Are you trying to complete from local CSS files?

**Comment by timurmelnikov** [comment]
Yes, from local files. All settings are default. In version 0.2.3 everything works.

**Comment by knpaing** [comment]
Same problem. With default settings, no CSS shows up. Will wait for next release. Meantime, will go with another extension. Thanks for the help.

**Comment by jasonchuot07** [comment]
> @jasonchuot07 Could you please tell us your settings? Are you trying to complete from local CSS files?

oh yeah sorry, I just reset all of my settings and returned to 0.2.3 and it worked, but the recent updates didn't

**Comment by ecmel** [comment]
Fixed in https://github.com/ecmel/vscode-html-css/commit/00546820178645e73df6c7e8a4b34e135d1ca0cf

**Comment by timurmelnikov** [comment]
Does not work. Made a video specially - https://www.youtube.com/watch?v=OXKiAJp9BH4&feature=youtu.be

**Comment by jasonchuot07** [comment]
> Does not work. Made a video specially - https://www.youtube.com/watch?v=OXKiAJp9BH4&feature=youtu.be

Yeah it didn't work for me either yesterday when I first returned to 0.2.3 but when I reset all of my settings and restarted vscode, it worked.
