### ISSUE TITLE
Support other html like documents

### ISSUE THREAD

**Issue by mhideadesign** [ecmel/vscode-html-css#182]
Hi,

Extension works well in html files. I can also add other files with 'files.associations' in settings like '*.blade.php'. But reactjs *.js files don't get suggestions. Tried Language modes javascript and javascriptreact and html .

**Comment by MahdiTa97** [comment]
I temporarily installed one of the previous versions: v0.2.3

**Comment by jasonchuot07** [comment]
> Hi,
> 
> Extension works well in html files. I can also add other files with 'files.associations' in settings like '*.blade.php'. But reactjs *.js files don't get suggestions. Tried Language modes javascript and javascriptreact and html .

Mine still works days ago but yesterday and today, it doesn't even recommend in html files, class names still didn't show up ... Have any idea how to fix this ?

**Comment by qq1147050160** [comment]
Me to!!

**Comment by ecmel** [comment]
@qq1147050160 Could you please tell more about your setup?

**Comment by qq1147050160** [comment]
@ecmel I use Local SCSS, which has been working normally before. When I started working on Monday, I found that it didn't work properly. In addition, I found that the configuration item in vscode:“ css.fileExtensions ": [" SCSS "] is no longer highlighted. (hint:  Unknown Configuration Setting)

**Comment by ecmel** [comment]
Fixed by https://github.com/ecmel/vscode-html-css/commit/42bc010babcc0ca2a72b4854bd76f8a290b73c34
