### ISSUE TITLE
ExtensionHost CPU usage goes up to 100% when enabling this extension

### ISSUE THREAD

**Issue by felipekb** [ecmel/vscode-html-css#185]
I've noticed that the CPU usage with this extension increases the CPU usage by a lot.

Tested by disabling it, got average numbers after that.

Here's the output of running `code --status`. 
```Version:          Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:46:53.673Z)
OS Version:       Darwin x64 20.1.0
CPUs:             Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)
Memory (System):  16.00GB (0.05GB free)
Load (avg):       4, 5, 5
VM:               0%
Screen Reader:    no
Process Argv:     . --crash-reporter-id ea953996-6f81-411f-ab56-0ceed96dff61
GPU Status:       2d_canvas:                  enabled
                  flash_3d:                   enabled
                  flash_stage3d:              enabled
                  flash_stage3d_baseline:     enabled
                  gpu_compositing:            enabled
                  metal:                      disabled_off
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          enabled
                  opengl:                     enabled_on
                  protected_video_decode:     unavailable_off
                  rasterization:              enabled
                  skia_renderer:              disabled_off_ok
                  video_decode:               enabled
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %	Mem MB	   PID	Process
    0	    82	 54085	code main
    0	    49	 54096	   gpu-process
    0	    16	 54098	   utility
   90	    82	 54104	   shared-process
    0	     0	 54519	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    1	   180	 54255	   window (update.rb — nanno-web)
  110	   115	 54257	     extensionHost
    0	    16	 54267	       electron_node server.js
    0	    33	 54261	     watcherService
    0	    16	 54263	     searchService```

**Comment by davisben** [comment]
I am experiencing the same behavior. Disabling the extension returns the CPU usage to normal.

**Comment by ecmel** [comment]
Is it high for startup or all the time?

**Comment by felipekb** [comment]
At all the time 🙃

**Comment by ecmel** [comment]
I am developing the extension on Windows 10 with WSL2 and my extension_host CPU usage is zero when idle.

**Comment by davisben** [comment]
I'm on MacOS 11.0.1. It stays at 100% until the extension is disabled.

**Comment by tonix-tuft** [comment]
Hello guys I have the same issue. 100% CPU usage when this extension is enabled.

I have disabled the extension for now.

Let me know when this issue is fixed cause I like this extension.

Cheers!

**Comment by ecmel** [comment]
@tonix-tuft  Are you on MacOS?

**Comment by tonix-tuft** [comment]
@ecmel Yes.

**Comment by ecmel** [comment]
Can be related to https://github.com/paulmillr/chokidar/issues/447

**Comment by ecmel** [comment]
@felipekb @davisben @tonix-tuft Could you please try version 1.1.4?

**Comment by tonix-tuft** [comment]
OK

**Comment by tonix-tuft** [comment]
Nope man, same issue for me 😢 

![312a9977712164959c4596d5164f2e45](https://user-images.githubusercontent.com/10134421/102022947-5e314300-3d8a-11eb-9884-7855c21334d1.gif)

![26a2aaf94791f8c4b0be0c08dbc224f3](https://user-images.githubusercontent.com/10134421/102022954-68ebd800-3d8a-11eb-8e75-fdfeeca9b224.gif)

**Comment by ecmel** [comment]
For reference Windows 10 with WSL 2:

```
Version:          Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS Version:       Windows_NT x64 10.0.19042
CPUs:             Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)
Memory (System):  15.81GB (7.08GB free)
VM:               0%
Screen Reader:    no
Process Argv:     --crash-reporter-id e6ce3f6e-cb76-49e1-8436-b2f5d71f705f
GPU Status:       2d_canvas:                  enabled
                  flash_3d:                   enabled
                  flash_stage3d:              enabled
                  flash_stage3d_baseline:     enabled
                  gpu_compositing:            enabled
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          disabled_off
                  opengl:                     enabled_on
                  protected_video_decode:     enabled
                  rasterization:              enabled
                  skia_renderer:              disabled_off_ok
                  video_decode:               enabled
                  vulkan:                     disabled_off
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %   Mem MB     PID  Process
    0       93    5060  code main
    0      189    4048     window (vscode-html-css [WSL: Ubuntu-20.04] - Visual Studio Code)
    0       94   16296       extensionHost
    0       64   21416         electron_node wslDaemon.js
    0       55    5828     crashpad-handler
    0       62    6884     utility
    0      108   13692     shared-process
    0      282   18048     gpu-process

Remote:           WSL: Ubuntu-20.04
OS Version:       Linux x64 4.19.128-microsoft-standard
CPUs:             Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)
Memory (System):  12.34GB (10.56GB free)
VM:               0%
CPU %   Mem MB     PID  Process
    0        0   22506  remote agent
    0        0   22743     watcherService
    0        0   22754     extensionHost
    0        0   22806     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0        0   22807       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

**Comment by tonix-tuft** [comment]
I don't know man, this is what I see on my Mac, something you can advise me to try in order to help further troubleshoot this issue?

**Comment by felipekb** [comment]
It seems to be working fine now! 

Thanks 👏 
![image](https://user-images.githubusercontent.com/28711924/102026715-2de3a780-3d7e-11eb-87a8-889ca9520e81.png)

**Comment by davisben** [comment]
I'm still seeing 100% with 1.1.4.

**Comment by tonix-tuft** [comment]
@davisben Same for me.

**Comment by tonix-tuft** [comment]
@felipekb Are you on OS X?

**Comment by ecmel** [comment]
@tonix-tuft Can you please try with `"css.watcherEnabled": false` setting in the 1.1.5 version?

**Comment by johnnywo** [comment]
same here MacOs Catalina 10.15.7

**Comment by felipekb** [comment]
@tonix-tuft Yes, Im running OS X 11.0.1

**Comment by tonix-tuft** [comment]
OK, it works `"css.watcherEnabled": false`, no CPU spikes.

Is there a way to disable this extension on a per-file basis? E.g. like Prettier does with `// prettier-ignore`?

I have a huge HTML file with some dumped data, maybe it's because of that...

**Comment by ecmel** [comment]
@tonix-tuft Where is your CSS? Are you using local or remote css? If remote then you dont have to enable watch setting

**Comment by tonix-tuft** [comment]
@ecmel It's local.

**Comment by ecmel** [comment]
@tonix-tuft You can use with absolute file names.

```
"css.ignoredFolders": [
  "**/node_modules/**"
]
```

**Comment by pilgunboris** [comment]
The same started happening to me today after the recent update of VScode (current version is 1.52.0). 
Current extension version: v1.1.5

Setting `"css.watcherEnabled": false` or disabling the extension resolves the issue.

Also, I had this previously:
```
"css.ignoredFolders": [
  "**/node_modules/**"
]
```
and it was still up to 300% CPU usage if that's helpful.

I'm on macOS 11.0.1.

**Comment by tonix-tuft** [comment]
@ecmel 

>@tonix-tuft You can enter absolute file names to css.ignoredFolders

How can I do this on a per-project basis? Can I put it in a project's`settings.json` file?

**Comment by ecmel** [comment]
@tonix-tuft Yes

**Comment by tautologistics** [comment]
Confirming that pegged processor is resolved with setting `"css.watcherEnabled": false`.
Observed the aberrant behavior with every permutation of the following:

* OS: OSX 11.0 & 11.1
* VS Code: 1.51 & 1.52
* HTML CSS Support: 1.1.4 & 1.1.5

All source files are local...

**Comment by shaal** [comment]
I have the same problem, on a MacBook Pro Catalina, VScode Insiders, CPU usage 100% when this extension is enabled :(

**Comment by ecmel** [comment]
Upstream bug reports:

https://github.com/paulmillr/chokidar/issues/859
https://github.com/paulmillr/chokidar/issues/873
https://github.com/paulmillr/chokidar/issues/447

**Comment by ecmel** [comment]
Anybody tried 1.1.6?

**Comment by tautologistics** [comment]
Just restarted the computer for unrelated reasons. Tried re-enabling `css.watcherEnabled` and the pegged CPU is back.

OSX: `11.1`
VS Code: `1.52.1`
HTML CSS Support: `1.1.6`

<img width="391" alt="image" src="https://user-images.githubusercontent.com/148452/102488590-4849a980-403a-11eb-916c-a0ca8adef661.png">

I know, it's not easy to diagnose and resolve someone else's issues asynchronously, but I do appreciate the effort you've put into creating/maintaining this extension and for looking into this issue. In the big picture, it's not a big deal because there's at least a means to mitigate the issue for now by disabling `css.watcherEnabled`.

**Comment by tonix-tuft** [comment]
Could it be related to VS Code's `1.52.0` minor version bump? What do you think guys?

**Comment by tautologistics** [comment]
> Could it be related to VS Code's `1.52.0` minor version bump? What do you think guys?

Possible but doubtful because I reverted to 1.51 to test and it still happened for me. That said, in theory 1.52 could have introduced new/changed user settings that contribute to this issue and reverting to 1.51 would therefore not undo that.

**Comment by ecmel** [comment]
Fixed in 1.2.0

**Comment by tonix-tuft** [comment]
No more `"css.watcherEnabled": false` in 1.2.0? I wanted to try the update and re-enable the watcher again, but the option is missing in VS Code after I updated the extension.

**Comment by ecmel** [comment]
Yes because there is no directory watcher. You can specify local and remote css files in a new settings (per workspace folder) `css.styleSheets.`

**Comment by tonix-tuft** [comment]
OK, so I if I have just updated the extension to 1.2.0 and I don't see CPU spikes anymore I am good to go, right? :)

**Comment by johnnywo** [comment]
Looks good now, thanks a lot!!
