### ISSUE TITLE
Workspace CSS loading issue

### ISSUE THREAD

**Issue by mehdad-hussain** [ecmel/vscode-html-css#187]
Hello, 
Your extension is great. I am using it for few months. But after recent update it's only working for remote stylesheets only in my case.
It can't fetch CSS class from my workbench folders anymore !!!
I don't know why it's happening.
Can you please help me with it ?

![Before recent Update](https://user-images.githubusercontent.com/73829310/102013154-93349a00-3d78-11eb-937c-6005618d935d.png)
Before this December update my vs code settings Jason file  was like this .

But after recent update it is now like this 
![After recent Update](https://user-images.githubusercontent.com/73829310/102013191-cb3bdd00-3d78-11eb-9536-43e110f7e63e.png)

`"css.fileExtensions": ["css", "scss"],`
this line is disabled now , and sadly I couldn't figure it out why it's disabled now :(

**Comment by ecmel** [comment]
Are you using CSS or SCSS files?

**Comment by mehdad-hussain** [comment]
I am using SCSS only for compiling CSS by other extension, before last update it was working fine. And in my main html I connecting only CSS files by script tags.

**Comment by mehdad-hussain** [comment]
Do you need my VS Code settings and extension list for debugging ?
Or anything I can help you with, though I am actually new in coding.

Or is it only occurring with me ? I am asking this because before this update when any file is open or associated with VS code I can't delete, move or any kind on change out of VS code. But now though that file is opened in VS code still I can delete that file !

**Comment by ecmel** [comment]
Can you please post your `<link>` tag and css settings?

**Comment by mehdad-hussain** [comment]
[https://github.com/mehdad-hussain/Furniture-E-Commerce](url)
this is one of my demo webstie .

    
    <link rel="stylesheet" href="assets/styles/bootstrap.css" />

    

    <link rel="stylesheet" href="assets/styles/style.css" />

[settings.zip](https://github.com/ecmel/vscode-html-css/files/5686600/settings.zip)

**Comment by ecmel** [comment]
Fixed in 1.2.0

**Comment by mehdad-hussain** [comment]
Thanks a lot for your hard work
