### ISSUE TITLE
not working with nunjucks files

### ISSUE THREAD

**Issue by hihahihahoho** [ecmel/vscode-html-css#188]
If i rollback to version 0.2.3 then it works fine, but not with the latest version

**Comment by ecmel** [comment]
Have you tried the following setting?

```json

"css.enabledLanguages": [
  "html",
  "nunjucks"
]
```

**Comment by hihahihahoho** [comment]
> Have you tried the following setting?
> 
> ```json
> "css.enabledLanguages": [
>   "html",
>   "nunjucks"
> ]
> ```

Yes i have tried it, but it did not work, only work with HTML files

**Comment by ecmel** [comment]
@hihahihahoho Can you please try 1.2.0?

**Comment by ecmel** [comment]
Also you can install https://marketplace.visualstudio.com/items?itemName=eseom.nunjucks-template and add language `"njk"`

**Comment by hihahihahoho** [comment]
i tried 1.3.2 but still does not work

**Comment by ecmel** [comment]
@hihahihahoho 

I installed https://marketplace.visualstudio.com/items?itemName=eseom.nunjucks-template. My settings:

```json
    "css.enabledLanguages": [
        "njk",
        "html"
    ]
```

It works in my case.
