### ISSUE TITLE
not working with pug file still 1.1.6

### ISSUE THREAD

**Issue by insight1111** [ecmel/vscode-html-css#189]
still 0.9.4 to 1.1.6, this plugin not work with pug.
I try setting below,

```
"css.enabledLanguages": [
  "html",
  "pug"
]
```

but not work yet.0.2.3 is working.

**Comment by ecmel** [comment]
Did you install pug extension?

**Comment by ecmel** [comment]
Please try "jade"
```
"css.enabledLanguages": [
  "html",
  "jade"
]
```

**Comment by insight1111** [comment]
I tried
```
"html","jade"
```
and
```
"html","pug","jade"
```

but not work...

**Comment by ecmel** [comment]
Can you try version 1.2.0?

**Comment by insight1111** [comment]
I tried 1.2.0.unfortunately,not work.
but log has no error.

**Comment by ecmel** [comment]
The following works in a file named `test.jade`:

```jade
a(class="accordion")
```

**Comment by insight1111** [comment]
can't work pug and jade in 1.2.1.
perhaps my environment dependent thing.
thank you.
