### ISSUE TITLE
css classes from node_modules aren't showing up

### ISSUE THREAD

**Issue by johnlindquist** [ecmel/vscode-html-css#19]
Now that `resource.json` is deprecated, I can't figure out how to reference a css file installed inside my `node_modules` folder. 

For example:
```node_modules/tachyons/css/tachyons.css```

I'm not sure if this is a bug or if there's something else that I need to configure now that resource.json is deprecated.

**Comment by ecmel** [comment]
I can not reproduce the problem, all css files under node_modules (as well as other directories) are parsed by the plugin and they show up in completion.

**Comment by johnlindquist** [comment]
Hmm, closing the editor then re-opening fixed it...
