### ISSUE TITLE
CSS Intellisense

### ISSUE THREAD

**Issue by knpaing** [ecmel/vscode-html-css#192]
Hello,

Thank you for the great extension. I have been using this since the beginning and with these new updates, I am not able to get intellisense from local css/scss files. I tried to read a lot but still I am not able to get it available. Please help.

Thank you.

**Comment by ecmel** [comment]
Thank you, please first of all note your local css files and create a file in your projects `.vscode` folder named `settings.json` with the flollowing contents:

```json
"css.styleSheets": [
  "css/bootstrap.css",
  "someOtherFolerRelativeToYourWorkspace/other.css" 
]
```

Hope this helps.

**Comment by knpaing** [comment]
Thank you. Before we did not need to do anything and it just worked. But with your new settings:

`{
  "css.styleSheets": [
    "./node_modules/bootstrap/dist/css/bootstrap.css",
    "./src/styles.scss"
  ]
}`

it is working now.

Regards.
