### ISSUE TITLE
Support for html tagged template like lit-html

### ISSUE THREAD

**Issue by blikblum** [ecmel/vscode-html-css#193]
Is there a way to get it working with lit-html, that uses tagged template literals?

Example:

```js
const render = () => {
  return html`<div class=""></div>`
}
```

Is not working when enabling and configuring "HTML CSS Support" with external stylesheet 

Using https://marketplace.visualstudio.com/items?itemName=runem.lit-plugin to do html syntax hihlight

**Comment by ecmel** [comment]
Please try enabling extension for `javascript` and/or `typescript` in `css.enabledLanguages`

**Comment by blikblum** [comment]
That did the trick.

Many thanks
