### ISSUE TITLE
Not working with React after 0.2.3

### ISSUE THREAD

**Issue by artuncolak** [ecmel/vscode-html-css#194]
CSS support not working with React (js, jsx, ts, tsx) after version 0.2.3.

```json
  "css.enabledLanguages": [
    "html",
    "javascriptreact",
    "typescriptreact",
    "typescript",
    "javascript"
  ],
```

**Comment by ecmel** [comment]
All of them works in my computer.

`css.enabledLanguages` is application scoped  so please be sure to set it in global settings and restart vscode.
