### ISSUE TITLE
Request for a VSCode changeling

### ISSUE THREAD

**Issue by niem94** [ecmel/vscode-html-css#195]
Given the frequent updates, it would be nice with a VSCode changelog, so we can see what is changing :-)

Creating a CHANGELOG.md in the root of the VSVode extension repository integrates automatically with VSCode, and all you need to do is provide some details in that file for each update. I suggest the following format (taken from one of my own extensions):

```md
# Change Log

## [0.0.7] - 2020-11-16

- New icon added
- Added Project Manager

## [0.0.5] - 2020-11-13

- Added Sort JSON Object, as it seems fitting for a base functionality in an IDE.

## [0.0.4] - 2020-11-13

- Removed Code Spell Checker - Danish, as this is only useful for Danes.

## [0.0.1] - 2020-11-11

- Initial release

```

**Comment by ecmel** [comment]
1.2.5 highlight is template inheritance support for mustache and twig like template engines.

**Comment by ecmel** [comment]
Added https://github.com/ecmel/vscode-html-css/commit/c6e614dc7bc2cf579cd0d4265d0a46c36eeeba49
