### ISSUE TITLE
Problems in VSCode in Twig templates with Tailwind CSS

### ISSUE THREAD

**Issue by hdevilbiss** [ecmel/vscode-html-css#197]
### Description of the problem

Overnight, I have tons of problems in my `.twig` templates, which were not present even 2 days ago; nothing in my configuration or UI framework has changed.

- The problems exist with [HTML CSS Support](https://marketplace.visualstudio.com/items?itemName=ecmel.vscode-html-css#review-details) installed in VSCode.

Here are a couple of the errors; these are thrown for every class name and id in all templates.

```
CSS class selector 'bg-white' not found
CSS class selector 'flex' not found
```

**header.twig**

```twig
<header class="header bg-white" >
  <div class="flex items-center justify-between px-3 pb-2">
    {% include "partial/base/logo.twig" %}
    {% include "partial/base/hamburger.twig" %}
  </div>
  <div class="wrapper">
    <nav id="nav-main" class="nav-main" role="navigation">
      {% include "menu.twig" with {'items': primary_menu.get_items} %}
    </nav>
  </div>
</header>
```

### Resolution

- The problem disappears with HTML CSS Suport uninstalled + reload VSCode.

### Log (Extension Host) Output in VSCode

I don't see any output errors.

```
[2020-12-26 17:03:01.903] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Hannah/.vscode/extensions/ecmel.vscode-html-css-1.4.1/dist/extension.js
```

### VSCode Version

<details>

```
Version: 1.52.1 (user setup)
Commit: <omitted>
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

</details>

Please let me know if you would like more information.

**Comment by ecmel** [comment]
Please check https://github.com/ecmel/vscode-html-css#additional-style-sheets

**Comment by demiavaliani** [comment]
> Please check https://github.com/ecmel/vscode-html-css#additional-style-sheets

Does not help. Made all the references and only few Problems disappeared.

**Comment by sansbacher** [comment]
I'm having the same issue, but not related to Twig or Tailwind or any CSS. Just a plain HTML file, all my id="something" are flagged in VSCode with "CSS id selector 'something' not found." Started a day or two ago.

If I disable or uninstall the HTML CSS Support extension the problem goes away. Restarting, reloading, etc. It's as if it is seeing any ID as a CSS ID. Win 10 x64, up to date VSCode and latest extension (I presume, I just uninstalled/reinstalled).

**Comment by leelhn2345** [comment]
I am having the same issue too for plain css/scss + html. 
All class + id selectors gave warnings.

The issue started with v1.4.1 onwards.

**Comment by ecmel** [comment]
Added a setting for validation warnings. Will be in the next release.

**Comment by leelhn2345** [comment]
Hi the problem still persists for me.

Im not sure if it's just me specifically though.

![image](https://user-images.githubusercontent.com/64735315/103197536-2c3ee580-4921-11eb-9b56-1d21cd04fd24.png)

Here's a snapshot if it helps.
