### ISSUE TITLE
CSS id Selector Not Found

### ISSUE THREAD

**Issue by dominait** [ecmel/vscode-html-css#198]
This is more of a question than an issue. Forgive me if I am using the wrong spot to get some help with the plugin.

I am having a hard time with the plugin warnings. Specifically  for id attributes that are being used with client side javascript  that never appear in any of the linked stylesheets.

I have searched through the documentation and looked through the VSCode settings to see if I could skip the warning for id selectors used solely as JavaScript hooks.

**Comment by leelhn2345** [comment]
hi, im facing this issues too. 

Im receiving warnings for all class and id selector

**Comment by Tenebraw** [comment]
Same here, working on a personal project using EJS and suddenly I have over 650 warnings, both for classes and id. I spent hours trying to figure out what the problem was. Apparently disabling "HTML CSS Support" in your extensions should solve the problem.

**Comment by ecmel** [comment]
Please see https://github.com/ecmel/vscode-html-css#selector-validation

**Comment by Cassidie** [comment]
> Please see https://github.com/ecmel/vscode-html-css#selector-validation

If you mean to say we now have to explicitly set css.styleSheets, css.validation, and css.enabledLanguages in our settings.json, then I couldn't get it to work bc I don't have any global styles. Plus, that would be such a hassle to have to do! I'm sure it's just a bug. For those that want to move on and get an immediate fix, simply downgrade to v1.3.3 until they fix it.

**Comment by ecmel** [comment]
css.enabledLanguages is one time global setting. If you do not need you can turn off css.validation globally as well.

**Comment by Audran-wol** [comment]
> Same here, working on a personal project using EJS and suddenly I have over 650 warnings, both for classes and id. I spent hours trying to figure out what the problem was. Apparently disabling "HTML CSS Support" in your extensions should solve the problem.

THATS really sad bro I had 1253 warning I thought the id selectors was already implemented in vs code

**Comment by Kruz1253** [comment]
I can't find my ID selector
