### ISSUE TITLE
Dont work in Angular 10

### ISSUE THREAD

**Issue by dmawesi** [ecmel/vscode-html-css#199]
Hello Ecmel,

Dont work for me in Angular 10. Marks warnings all classes

Here my conf

{
    "css.styleSheets": [
        "src/styles.css",
        "node_modules/bootstrap/dist/css/bootstrap.min.css",
        "node_modules/@fortawesome/fontawesome-free/css/all.css"
    ]
}

My HTML code

<i class="m-5 fa fa-file" aria-hidden="true"></i>

![image](https://user-images.githubusercontent.com/74744398/103191117-a4fe5d00-48a1-11eb-9b4a-c40e1dbad19c.png)

![image](https://user-images.githubusercontent.com/74744398/103191185-09b9b780-48a2-11eb-9f92-e4d2135f7455.png)

I appreciate your help

Thank you

**Comment by ecmel** [comment]
With your exact settings and npm install `@fortawesome/fontawesome-free` and `bootstrap` works for me.

**Comment by demiavaliani** [comment]
Hi,

I'm on Angular 11. Added all the possible CSS paths. Some Problems disappeared, but some still stayed.

![Capture2](https://user-images.githubusercontent.com/33201116/103215613-8e491c00-491c-11eb-8acc-b841afe2e04a.PNG)
![Capture](https://user-images.githubusercontent.com/33201116/103215614-8ee1b280-491c-11eb-8425-dff7df49aa87.PNG)
![Capture1](https://user-images.githubusercontent.com/33201116/103215616-8f7a4900-491c-11eb-820c-772b50259c74.PNG)

**Comment by dmawesi** [comment]
Hello Ecmel,

**Now if it works perfect for angular,**

I solved it this way thanks to plohoj:

![image](https://user-images.githubusercontent.com/74744398/103289365-0105d600-49b5-11eb-862f-7c7ad8a21f33.png)

![image](https://user-images.githubusercontent.com/74744398/103289420-2266c200-49b5-11eb-905b-d015a88c4a64.png)



Thanks for your attention

**Comment by demiavaliani** [comment]
That actually solved most of the problems. But still, some class names have Problems. So I guess not fully fixed.

**Comment by dmawesi** [comment]
> That actually solved most of the problems. But still, some class names have Problems. So I guess not fully fixed.

Hi demiavaliani,

I tested it with your code

![image](https://user-images.githubusercontent.com/74744398/103291051-f2212280-49b8-11eb-9909-c6705c94174e.png)


Try with this setting:

![image](https://user-images.githubusercontent.com/74744398/103291161-24328480-49b9-11eb-8a5a-0781a2f6ae0a.png)

**Comment by demiavaliani** [comment]
Check this. Unfortunately one class name is still with Problem.

![image](https://user-images.githubusercontent.com/33201116/103294401-7942ba80-49fa-11eb-853d-44e4bd9340f9.png)

![image](https://user-images.githubusercontent.com/33201116/103294647-ed7d5e00-49fa-11eb-8b8a-c4f2291b9078.png)

**Comment by dmawesi** [comment]
Hi demiavaliani,

Where is the defined class you are placing?

![image](https://user-images.githubusercontent.com/74744398/103298661-ce65d880-49c8-11eb-9ccb-2c45347fc952.png)

**Comment by demiavaliani** [comment]
`menu-btn-icon` is not a bootstrap class. It's my custom class name in `/navigation.component.css`

**Comment by dmawesi** [comment]
Hi demiavaliani

Try this,

just locate where your css is and configure in that folder

![image](https://user-images.githubusercontent.com/74744398/103305557-6d92cc00-49d9-11eb-845b-c180f07ebd75.png)

**Comment by demiavaliani** [comment]
Tried, and believe me, I tried every kind of formatting and nothing is helping. That one Problem is just does not disappear.

**Comment by dmawesi** [comment]
In which folder is the navigation.component.css file? Show me a screenshot

**Comment by demiavaliani** [comment]
![image](https://user-images.githubusercontent.com/33201116/103346064-b743eb00-4a9b-11eb-9947-0bc30410db5e.png)

**Comment by dmawesi** [comment]
Did you close and open the VS?

**Comment by demiavaliani** [comment]
Yup, restarted VS many times. Adjusted the path in all the different ways and one Problem is still hanging.

**Comment by BStanchevArena** [comment]
I'm having the same problem no matter what I do I always get warnings 
![Code_dcf6lDFj65](https://user-images.githubusercontent.com/70687265/103521671-d4a0fc80-4e81-11eb-9fea-04b409051d19.png)

**Comment by demiavaliani** [comment]
Finally managed to solve. All Problems disappeared!!!

In settings.json in css.validation set both "id" and "class" to false.

![image](https://user-images.githubusercontent.com/33201116/103664915-76584480-4f7b-11eb-9cf7-417a85371636.png)

**Comment by gsacavdm** [comment]
@demiavaliani - so you disabled validation but still get auto complete?

In my case, with the initial `/` in the path, validation works, but auto-complete doesn't.

**Comment by ecmel** [comment]
Please upgrade to version 1.8
