### ISSUE TITLE
Support for blade

### ISSUE THREAD

**Issue by TheColorRed** [ecmel/vscode-html-css#2]
I have the blade plugin, so it would be nice if the `blade` language id was supported too.

**Comment by ecmel** [comment]
Can you provide the link for the plugin?

**Comment by TheColorRed** [comment]
https://marketplace.visualstudio.com/items?itemName=KTamas.laravel-blade

**Comment by ecmel** [comment]
Added in version 0.0.18

Can you please test?

**Comment by TheColorRed** [comment]
It looks like it is working!
