### ISSUE TITLE
Suggestion list works only with ctrl+space in VS Code 1.11.1

### ISSUE THREAD

**Issue by florianbouvot** [ecmel/vscode-html-css#20]
The suggestions list doesn't appear automatically, only if pressing `ctrl` + `space`.

* macOS 10.12.4
* VSCode 1.11.1

**Comment by andersea** [comment]
Not really a bug, as we found out. It's due to this:

https://code.visualstudio.com/updates/v1_11#_intellisense-in-comments

See also:

* Microsoft/vscode#24464
* andersea/HTMLClassSuggestionsVSCode#9
* Zignd/HTML-CSS-Class-Completion#43

**Comment by ecmel** [comment]
Thank you very much for spotting the problem.

Closing this.

**Comment by tonypig93** [comment]
@andersea solved my problem, thanks.
