### ISSUE TITLE
Add an 'Ignore warning setting'

### ISSUE THREAD

**Issue by shreym03** [ecmel/vscode-html-css#201]
I'm currently using ejs to make HTML templated and II get a giant amount of warnings because it cannot find CSS tags or because I use id to label some of my components. I  get it's for efficiency but I wiish I would stop getting 30- 40 warnings for a link that is in another template

**Comment by ecmel** [comment]
Please use css.validation setting to disable warnings

**Comment by ecmel** [comment]
https://github.com/ecmel/vscode-html-css#selector-validation
