### ISSUE TITLE
CSS class selector not found error.

### ISSUE THREAD

**Issue by ksaravindakashyap** [ecmel/vscode-html-css#202]
Even though all my html class are linked with CSS, it is showing CSS selector not found error for all the class.
The video recording is attached below. The same code is working for older version, but for new version it is not supporting. Can anyone help me with this? Thank you.

https://user-images.githubusercontent.com/68753937/103421186-0e8fab80-4bc1-11eb-9b28-36033b227ef1.mp4

Can anyone review this?

**Comment by makabeus** [comment]
Something is wrong with class names with hypens (like yours "header-branch").
For me cache classes button is doing nothing, to update I need to save the .css file.
Removing hypen, saving file, adding hypen again, fix 'not found selector' error (alomst every time :p) .
I could not manage to figure out the exact sequence though.  ¯\_(ツ)_/¯

**Comment by ksaravindakashyap** [comment]
@makabeus  Even if the hyphen is removed the error remains the same!. A problem with newer version 1.6.1 for the older versions were it was working perfectly.

**Comment by ecmel** [comment]
{% static 'css/style.css' %} is not supported yet.

Can you please add style.css to https://github.com/ecmel/vscode-html-css#additional-style-sheets

**Comment by ksaravindakashyap** [comment]
@ecmel  I tried but didn't help. Can you review the image attached below
![Screenshot (427)_LI](https://user-images.githubusercontent.com/68753937/103454785-59b6d500-4d0d-11eb-81e0-e70eb4702537.jpg)

Even I tried to add style.css in README.md (and changed back to the original form as it didn't workout) and .vscode/settings.json (in my current project working environment ).

**Comment by ecmel** [comment]
Please just include the setting in the curly brackets. Also remove the comments:

```json
{
    "css.styleSheets": [
        "./style.css"
    ]
}
```
