### ISSUE TITLE
CSS class not found.

### ISSUE THREAD

**Issue by lucianobarauna** [ecmel/vscode-html-css#204]
Hi.

Congratulations on the extension :-)

Well, I already read the documentation, followed the steps to try to map the specific path and even then this error is being presented.

I wanted to know where I'm going wrong.

I'm using Gulp as a task automator. You can see that in the html `link` tag I am using an` @ asset_folder`. I need this because of a peculiarity of the project which is to have different types of thema for css, because of that I need to map the file `lms.scss`.

I did not put the directory structure because I think the print is already well explained.

I even looked at this issue https://github.com/ecmel/vscode-html-css/issues/202 before but I didn't have much success.

![img-error](https://user-images.githubusercontent.com/1054454/103562213-7849d700-4e99-11eb-80ba-acb334415ae1.png)

**Comment by ecmel** [comment]
Please upgrade to version 1.8
