### ISSUE TITLE
CSS class selector 'xyz' not found.

### ISSUE THREAD

**Issue by mpoirier101** [ecmel/vscode-html-css#207]
Issue Type: <b>Bug</b>

Extension displays useless error message when unreferenced class name is used in html file.

Extension version: 1.6.3
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440:30242242
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773cf:30236630
vsjup459cf:30237188

```

</details>

**Comment by ecmel** [comment]
Please upgrade to 1.7
