### ISSUE TITLE
Using with Angular?

### ISSUE THREAD

**Issue by sagerio** [ecmel/vscode-html-css#208]
The last version this extension was working correctly with Angular was 1.2.1 (in my experience).
Since then, every 2 days a new version poped up, but never worked with Angular.

Do I have to stick with 1.2.1 or can I get the latest extensions running with Angular?

**Comment by ecmel** [comment]
Are you using remote or local styles?

**Comment by sagerio** [comment]
Local styles under `src/assets/some-style.css`

I've tried this solution in settings.json:

    "css.styleSheets": [
        "src/assets/some-style.css",
        "src/assets/some-other-style.css"
    ]

But without luck, Intelisense shows nothing...

**Comment by ecmel** [comment]
Please try with a leading dash like "/src/assets"

**Comment by sagerio** [comment]
That works, thanks! :thumbsup:
Is there a way to include the css files for all the components, like `/src/app/**/*.css` or something?

**Comment by ecmel** [comment]
Where is the angular file located?

**Comment by sagerio** [comment]
You mean the angular.json?

**Comment by ecmel** [comment]
No I mean the file which you use intellisense?

If it is e.g. `app/app.component.html` and you want to use `app/app.component.css` then you should use `./app.component.css` in the settings.

**Comment by sagerio** [comment]
Exactly this, `name.component.html` and in the same folder `name.component.css`

If I have multiple components like so

    comp1\
        comp1.html
        comp1.css

    comp2\
        comp2.html
        comp2.css

    comp3\
        comp3.html
        comp3.css

do I have to provide the following?

```
"css.styleSheets": [
    "./comp1.css",
    "./comp2.css",
    "./comp3.css",
]
```

**Comment by ecmel** [comment]
Yes exactly

**Comment by sagerio** [comment]
Great, thank you very much!

**Comment by ecmel** [comment]
@sagerio You can also use the following starting with 1.8.1:

```json
{
    "css.styleSheets": [
        "${fileBasenameNoExtension}.css"
    ]
}
```
