### ISSUE TITLE
Support for remote stylesheets

### ISSUE THREAD

**Issue by TheColorRed** [ecmel/vscode-html-css#21]
It would be nice if I could place a list of remote css files in the settings of the current project.

So in `.vscode/settings.json` I could have something like this:

```json
{
    "css.dependencies": [
        "https://cdn.remote.com/bootstrap.css",
        "https://cdn.google.com/mdl/material.css"
    ]
}
```

Then when I used the plugin, I could get a list of class names from one or more remote cdn's.

**Comment by ecmel** [comment]
Added in 0.1.2
