### ISSUE TITLE
Can't use css.enabledLanguages via workspace settings

### ISSUE THREAD

**Issue by lonix1** [ecmel/vscode-html-css#210]
I place all my settings in `/.vscode/settings.json` so they can be added to source control.

But the `css.enabledLanguages` setting isn't respected, and the error is
> This setting can be applied only in application user settings

Why is that?

**Comment by ecmel** [comment]
This setting is application scoped.

Please check https://github.com/ecmel/vscode-html-css#supported-languages

**Comment by lonix1** [comment]
Thanks :smile:  Yeah I saw that:
> This setting is application scoped and changing the setting requires restarting VS Code.

But what I mean is why is it like that... why can't it work as a workspace setting?

**Comment by ecmel** [comment]
The languages array is registered when the extension is activated so it will not register if you use multiple workspace folders due to how VS Code works.

**Comment by lonix1** [comment]
Okay I get it now! Thanks!
