### ISSUE TITLE
Extension stopped providing suggestions for HTML class attributes?

### ISSUE THREAD

**Issue by inliquid** [ecmel/vscode-html-css#212]
Since some moment it just stopped working:

![изображение](https://user-images.githubusercontent.com/6797881/106306166-b787ff80-626e-11eb-8eb8-9e17df2deb13.png)
![изображение](https://user-images.githubusercontent.com/6797881/106306344-fb7b0480-626e-11eb-96ce-2507ea74df23.png)

**Comment by nsmithdev** [comment]
I'm having the same problem in an Angular project using .scss
Downgrading to version v0.2.3 of the plug-in restores suggestions for my project.

**Comment by djeu007** [comment]
Same problem here.
Extension stopped to work few days ago.
Downgrading to version v0.2.3 solves the problem.

**Comment by ecmel** [comment]
Should work in 1.14.0
