### ISSUE TITLE
Please publish extension to open-vsx.org (or please provide an official .vsix release)

### ISSUE THREAD

**Issue by jankeromnes** [ecmel/vscode-html-css#213]
Hello! 👋 

Could you please publish `ecmel.vscode-html-css` to the open-source registry https://open-vsx.org?

- This would allow users from non-Microsoft editors like VSCodium, Gitpod, Theia, etc. to install and use your open-source extension

- It just requires getting a [token](https://open-vsx.org/user-settings/tokens) and adding `npx ovsx publish` to any existing VSCode Marketplace publishing script (same tech)

---

Alternatively, could you please provide an official `.vsix` binary, e.g. by uploading it as an asset in your GitHub Releases? (This would make re-publishing ourselves more convenient, in case you don't want to publish to OpenVSX.)

**Comment by ecmel** [comment]
Sure I will
