### ISSUE TITLE
Not providing Suggestions.

### ISSUE THREAD

**Issue by abhyuday-tripathi** [ecmel/vscode-html-css#214]
# VERY BAD
## I have installed it just now and it is not working

**Comment by yaegassy** [comment]
@abhyuday-tripathi It works fine in my environment. I think it's a problem with your environment and settings.

**Comment by abhyuday-tripathi** [comment]
# There is no problem in my environment.

## I have installed a different Extension similar to this. 

## That works fine for me

**Comment by udhayaas97** [comment]
Yes for me too not working

**Comment by udhayaas97** [comment]
> # VERY BAD
> ## I have installed it just now and it is not working

Add the CSS files in settings.json like this
"css.styleSheets": [
    "https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
  ]

**Comment by abhyuday-tripathi** [comment]
> > # VERY BAD
> > ## I have installed it just now and it is not working
> 
> Add the CSS files in settings.json like this
> "css.styleSheets": [
> "https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
> ]

Already Added that but now using another extension
