### ISSUE TITLE
Enabling django html doesn't work

### ISSUE THREAD

**Issue by Mosek12** [ecmel/vscode-html-css#218]
![Zrzut ekranu 2021-03-26 130737](https://user-images.githubusercontent.com/79460068/112629164-3a26d880-8e34-11eb-8820-bed07ae5b6c7.png)
Am I doing something wrong?

**Comment by mdsadiqueinam** [comment]
you should place this in your vscode setting then it might works

**Comment by mdsadiqueinam** [comment]
HTML IntelliSense in not working on django-html is there any way to implement the HTML IntelliSense to django-html

**Comment by CodelineRed** [comment]
I'm not familiar with Django. Is django-html the file extension?

This is how i did it with files ending with `*.vue`:
Go to: File > Preferences > Settings > (Tab) User > Extension > CSS Settings
CSS: Enabled Languages > Edit in settings.json
Insert:
```json
{
    "css.enabledLanguages": [
        "vue",
        "html"
    ]
}
```
Restart VScode.
Move cursor to HTML class attribute and press CTRL + Space (on winwows) for autocompletion
