### ISSUE TITLE
NOT SUPPORTING CSS

### ISSUE THREAD

**Issue by Abhishay** [ecmel/vscode-html-css#228]
Issue Type: <b>Bug</b>

I HAVE DOWNLOADED ONE EXTENSION BUT ITS SAYING NO EXTIONS FOUND
SO I DOWNLOADED ALL THE EXTENSIONS AND ALSO ITS SAYING NOT DETECTED

PLZ HELPME I AM NEW TO VS CODE

Extension version: 1.10.2
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.67GB free)|
|Process Argv|--crash-reporter-id 86968fd7-a5a1-4714-898b-4ff7b6abc11c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30301613
vscorehov:30302759
bridgeflightcf:30302070
vscod805cf:30301675

```

</details>

**Comment by gxmzjxk** [comment]
When i revert to old `0.2.3` and use `css.remoteStyleSheets`，everything works fine !

**Comment by ecmel** [comment]
Should work in 1.14.0
