### ISSUE TITLE
In-file suggestions is not available

### ISSUE THREAD

**Issue by Grawl** [ecmel/vscode-html-css#23]
When this plugin is enabled, there is no in-file words suggested.

Pug files, OS X, VS Code 1.11.2

**Comment by ecmel** [comment]
Can you please try the workaround in https://github.com/ecmel/vscode-html-css/issues/20

**Comment by TheColorRed** [comment]
You can also use Emmet syntax which has suggestions: https://emmet.io/

**Comment by Grawl** [comment]
@ecmel no it's not working for me. All I see in suggestions is CSS classes but not variables from current document.

This issue is faced in Vue files also.

**Comment by ecmel** [comment]
Inline classes defined in style tags comes up in completion both for html and vue files.

**Comment by Grawl** [comment]
> but not variables from current document.

**Comment by ecmel** [comment]
This may be a vs code issue. Can you disable this extension and try again?

**Comment by Grawl** [comment]
I've found a working extension https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion
