### ISSUE TITLE
Is possible to add support for CSS-in-JS(X) with React?

### ISSUE THREAD

**Issue by iFwu** [ecmel/vscode-html-css#24]
Hello, thanks for creating this practice extension.
I'm using react so there are many possible ways to add css style in js(x) file, most of them use normal css syntax. For example, [styled-jsx](https://github.com/zeit/styled-jsx), [styled-components](https://github.com/styled-components/styled-components)...

Is there any possibility to add support for such project? Or, I can fork this repo to create respective extensions for those.

**Comment by ecmel** [comment]
Pull requests are welcomed, if u prefer you can fork this repo and create a new extension.

**Comment by ecmel** [comment]
Does https://github.com/ecmel/vscode-html-css/pull/32 fix this?

**Comment by rush1818** [comment]
#32 will work if the file's language mode is `JavaScript React`
