### ISSUE TITLE
link "css.styleSheets" to several css files or dir

### ISSUE THREAD

**Issue by CMQNordic** [ecmel/vscode-html-css#243]
Unsure if its a bug or just not supported?
As often run webpack project with css bundling I want to search for class definitions in several css files in a folders not linked in index.html.

Should something similar to this work? If not would be awesome if it coud be added added...

    "css.styleSheets": [
        "/styles/**{"css", "scss"},
    ]

**Comment by ecmel** [comment]
Hello, please see following:

https://github.com/ecmel/vscode-html-css#additional-style-sheets

**Comment by CMQNordic** [comment]
So as I understand by the comment to read above there is NO support to scan several css files as it is not desribed there?

Or is it just not in the documentation. any plans for such a functionality to scan several css files in a desired folder?

**Comment by ecmel** [comment]
Should work in 1.14.0
