### ISSUE TITLE
Consider on-boarding to VS Code Sponsorship

### ISSUE THREAD

**Issue by isidorn** [ecmel/vscode-html-css#247]
Hi VS Code PM here 👋 

Consider on-boarding to VS Code sponsorship. It is as easy as adding:
```json
"sponsor": {
  "url": "https://www.buymeacoffee.com/ecmel"
}
```

to your `package.json`

More details here
https://github.com/microsoft/vscode-discussions/discussions/14

**Comment by ecmel** [comment]
Thank you very much it is added
