### ISSUE TITLE
IDs and classes contained in HTML aren't automatically revealed in CSS

### ISSUE THREAD

**Issue by kinn81** [ecmel/vscode-html-css#248]
Apologies if I'm misinterpreting what this extension does or not using it correctly. I've installed the extension, VS Code says its running, but id's and classes contained in the associated HTML file do not autocomplete in the CSS file - typing either **#** or **.** does nothing.
![image](https://user-images.githubusercontent.com/78006756/176643082-8f8e11c3-4e48-4df7-b728-b3a9e4723870.png)
![image](https://user-images.githubusercontent.com/78006756/176643203-0113fd1f-075e-4794-a26b-75bcdcc5c06e.png)

**Comment by ghaschel** [comment]
I believe this extension provides only the other way around

**Comment by SergioChizhikov** [comment]
I don't understand at all how to get this plugin to work. Why did so many people install it? Does it work for you? Tell everyone how did you do it?
Doesn't work with external style file, doesn't work with <style><style/>...

**Comment by ghaschel** [comment]
@SergioChizhikov this extension allow you to have class and id suggestions of the ones you have in your stylesheet, but inside html class attributes.

**Comment by SergioChizhikov** [comment]
@ghaschel I'm really stupid.) Thank you friend!
