### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by Will-Bill** [ecmel/vscode-html-css#25]
I am having difficulty getting this to work. I am using VS Code on MacOS with Dotnet Core 1.1 (cshtml/razor).

I installed the plugin as per "ext install vscode-html-css" but my CSS classes do not show when inside a .cshtml file and typing class="" or similar.

I tried adding an external CSS reference to .vscode/settings.json also but that hasn't worked:

"css.remoteStyleSheets": [
        "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
    ]

I installed "npm install -g --save vscode-css-languageservice" also. 

I have tried uninstalling and reinstalling to no avail. Could another plugin be causing issues? Or have I missed a blatantly obvious step?

**Comment by ecmel** [comment]
Can you please press Ctrl + Space inside class="".

Also check https://github.com/ecmel/vscode-html-css/issues/20

**Comment by Will-Bill** [comment]
Thats the one, thanks!
