### ISSUE TITLE
ctrl+space 

### ISSUE THREAD

**Issue by malaquro** [ecmel/vscode-html-css#254]
does not work on Mac Os
I tried control and command+space. What can be done about it?

"Visual Studio Code CSS Intellisense for HTML"

**Comment by ecmel** [comment]
Hello, what is the extension of the file you are working on? (html, php etc)

**Comment by malaquro** [comment]
html
<input type="">  or
css
body {
    background-repeat: ;
}

on windows, pressing control+space displays view a list of id and class attribute suggestions via ctrl + space. It doesn't work on mac os and I want to figure out what to do

**Comment by ecmel** [comment]
Please try this https://github.com/ecmel/vscode-html-css#additional-style-sheets

**Comment by malaquro** [comment]
What exactly?

The task is simple, ctrl+space works on Windows, not on Mac Os! What keyboard shortcut works or how to change it for this extension???

**Comment by ecmel** [comment]
What is the source of your CSS? Is it loading from internet or the project itself?
