### ISSUE TITLE
Theme colors may be added

### ISSUE THREAD

**Issue by DeznekCZ** [ecmel/vscode-html-css#255]
Hello devs.

Can be added support for these colors accepted by browsers:

Background, InfoText, CaptionText, ActiveCaption, ActiveBorder, InactiveCaptionText, InactiveBorder, InactiveCaption

These colors are automatically filled by (at least Microsoft Edge) browsers and use default colors based on selected page theme.

![image](https://user-images.githubusercontent.com/9643627/187022186-1ec3111e-f4b0-4ef6-8ff5-69588b52883a.png)

Thank you for any help

**Comment by ecmel** [comment]
Not related with this extension
