### ISSUE TITLE
have a problem about class compelete in *.vue

### ISSUE THREAD

**Issue by NaccOll** [ecmel/vscode-html-css#26]
## Env

- VSCode Version: 1.12.1
- OS Version: Windows 10 64bit
- Node Version

## Problem

The class suggestion work outside of the html in some file. As follows:
[![https://gyazo.com/a6e4d76157e9dd6d6522fd14636888d5](https://i.gyazo.com/a6e4d76157e9dd6d6522fd14636888d5.png)](https://gyazo.com/a6e4d76157e9dd6d6522fd14636888d5)

## Steps to Reproduce
1. 
```shell
npm install vue-cli 
```
2.
```shell
vue init webpack test
```
3.
```shell
cd test
npm install
```
4. create a new file named Test.vue in /src/components/
```vue
<template>
  <div>test</div>
</template>

<script>
export default {
  name: 'Test'
}
</script>

<style>

</style>

```
5. this is normal.
[![https://gyazo.com/7d1f2919244085cd3dc05486590575ae](https://i.gyazo.com/7d1f2919244085cd3dc05486590575ae.png)](https://gyazo.com/7d1f2919244085cd3dc05486590575ae)

6. this is abnormal.
[![https://gyazo.com/35fadbb98983d0cbf11271618ea0cbe8](https://i.gyazo.com/35fadbb98983d0cbf11271618ea0cbe8.png)](https://gyazo.com/35fadbb98983d0cbf11271618ea0cbe8)

This problem will appear when I import other files.

In addition, I meet it in Hello.vue. As follows:
[![https://gyazo.com/23a236cf7790ac985f13512313b60367](https://i.gyazo.com/23a236cf7790ac985f13512313b60367.png)](https://gyazo.com/23a236cf7790ac985f13512313b60367)

However, it is not always.
[![https://gyazo.com/9c4f4dbcd16a0eb2980d2f230db5b7fc](https://i.gyazo.com/9c4f4dbcd16a0eb2980d2f230db5b7fc.png)](https://gyazo.com/9c4f4dbcd16a0eb2980d2f230db5b7fc)
or
[![https://gyazo.com/37b084d0de446930e73e14769935c0da](https://i.gyazo.com/37b084d0de446930e73e14769935c0da.png)](https://gyazo.com/37b084d0de446930e73e14769935c0da)

**Comment by hh233** [comment]
Did you find a solution

**Comment by NaccOll** [comment]
@hh233 
Sorry, I don't have any solutions. 
Perhaps, you can use [IntelliSense for CSS class names](https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion).
But it don't support emmet.

**Comment by hh233** [comment]
@NaccOll 
Thank you! I'm edited with pug, [IntelliSense for CSS class names](https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion) also doesn't support pug
