### ISSUE TITLE
Prerequisites for template inheritance?

### ISSUE THREAD

**Issue by truckee** [ecmel/vscode-html-css#260]
Are there prerequisites for template inheritance? I ask because it does not appear to work in VSC. I'm familiar with Symfony\Twig and the use of `{% extend "templates/base.html.twig %}`. Yet I am unable to reproduce the effect in VSC. For example:
```
{% extends "base.html" %}
{% block body %}
booga wooga
{% endblock %}
```
 is rendered as 
`{% extends "base.html" %} {% block body %} booga wooga {% endblock %}` even though `base.html` contains
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Castle Rock HOA</title>
        <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    </head>
    <body>
        {% block body %}
        {% endblock body %}
    </body>
</html>
```

**Comment by ecmel** [comment]
There are no prerequisites using version 2.0.0 of the extension. In your case just put `assets/css/bootstrap.min.css` in `.vscode/settings.json`
