### ISSUE TITLE
.erb files not working

### ISSUE THREAD

**Issue by finnove** [ecmel/vscode-html-css#274]
![Bilde_2023-11-27_155504756](https://github.com/ecmel/vscode-html-css/assets/1630604/c5ff166f-c8b2-48d1-958f-0c6aa64c34b0)
Cannot get this to work on html.erb files. I expected this to work out of the box, but also tried to add
   "emmet.includeLanguages": {
        "html.erb": "html",
        "erb": "html"
    }

no difference. When using .html it works. Does not work with .html.erb or just .erb. Is this just me?

Or is my expected result (see picture) coming from the vs code built in features and not from this extention?

**Comment by ecmel** [comment]
Please check the readme for adding language support.
