### ISSUE TITLE
Nested selectors highlighting

### ISSUE THREAD

**Issue by jrom99** [ecmel/vscode-html-css#276]
The scopes `entity.name.tag.css` and `meta.selector.css` are missing when a nested selector is used. This problem extends to pseudo-classes and property names.

![image](https://github.com/ecmel/vscode-html-css/assets/47498278/87f7aa64-6e87-4597-8933-6d4e6fcdccb5) ![image](https://github.com/ecmel/vscode-html-css/assets/47498278/a3da9ca6-afe0-4a3f-8212-d124ada049c8)

![image](https://github.com/ecmel/vscode-html-css/assets/47498278/ab80858c-387e-464a-b954-1e673803f792)

![image](https://github.com/ecmel/vscode-html-css/assets/47498278/47ce0e89-a3dd-49ad-a8dc-a3503386548d)

## System information

HTML CSS Support: v1.13.1

Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:47:11.635Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.5.0-14-generic

**Comment by ecmel** [comment]
This extension does not do any highlighting for CSS. It completes class and id attributes in html.

**Comment by jrom99** [comment]
Isn't the lack of highlighting due to the lack of provided scopes?

**Comment by ecmel** [comment]
Please try version 2.0.0

**Comment by jrom99** [comment]
The issue continues as described, the nested selector `h2` has the same scope as in the other screenshot.

![image](https://github.com/ecmel/vscode-html-css/assets/47498278/154363c7-4b42-42e1-8ea2-4ee1becebac5)

## System information:

HTML CSS Support: v2.0.0
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:47:11.635Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.5.0-14-generic

**Comment by ecmel** [comment]
There are no class or id selector in your screenshots.

**Comment by jrom99** [comment]
I'm aware, the original issue is about the selectors (`h2`, `:hover`) themselves not having any highlight, since they are more important to me than a property highlight (`border-top-left-radius`). In the screenshot below, you can see that the second `h2` selector has the scope `entity.name.tag.css`, which is not present in the first.


![image](https://github.com/ecmel/vscode-html-css/assets/47498278/fe5053bc-a50d-4904-97a2-825bff9ccceb)

**Comment by ecmel** [comment]
I think this problem is not related with this extension. Which style selector are your trying to complete? Can you post the relevant css and completion code here

**Comment by ecmel** [comment]
Extension only offers completion for class (.) and id (#) selectors.

**Comment by jrom99** [comment]
I'm sorry, I thought this extension was responsible for providing scopes for CSS in VS Code. Thank you for the prompt replies.
