### ISSUE TITLE
v1.14.1 Suddenly Stopped Working

### ISSUE THREAD

**Issue by danielgesua** [ecmel/vscode-html-css#277]
Hi guys,

Just a heads up. I was using the extension and things suddenly got slow, then stopped showing suggestions altogether. I tried:
 - Restarting my workstation [failed to solve]
 - Uninstalling and installing the extension [failed to solve]
 - Disabling other extensions [failed to solve]
 - Clean uninstalling vs-code and reinstalling [failed to solve]
 - Testing on a different (smaller) project [problem was still there]

Then I realized there was a recent patch and it gave me the idea to roll back to the previous version. Sure enough the problem is fixed!

For context:
OS: Windows 10 Pro X64
These are my installed extensions...  
![image](https://github.com/ecmel/vscode-html-css/assets/51037699/80f304cc-6d46-455a-8e53-972039434c28)

I don't personally need a fix since I'm oaky with the previous version, but just figured you'd appreciate the feedback as you troubleshoot.

Best,
DG

**Comment by ecmel** [comment]
Hi there, have you tried version 1.14.1?

**Comment by ecmel** [comment]
Please try version 2.0.0

**Comment by danielgesua** [comment]
Hi Ecmel,

Sorry for the delay. When I get back to work I'll try it out.

Sorry. I did't understand your previous question. Would you care to explain?

Thanks,
DG

**Comment by danielgesua** [comment]
Hi Ecmel,

Tried upgrading to 2.0.0 and it stopped working again. Now even if I roll it back to the older patch it isn't working.

What should I do?

Thanks,
DG

**Comment by ecmel** [comment]
Can you tell me more about your project structure, I mean how do you use this extension? On which files?

**Comment by danielgesua** [comment]
Its a Flask application and I'm using it on the index.html file (A jinja template for the home page). I tried 1.4.1, 1.4.0, 2.0.0 and 2.0.6. It provides me with intellisense for bootstrap and my own CSS files. 

The project structure is a pretty standard flask structure with index.html residing in the templates folder, and all my CSS, JS and other static assets inside a separate "static" folder.

**Comment by ecmel** [comment]
Thanks for the info, what is the contents of your project's `.vscode/settings.json` file? You should have a key `"css.styleSheets"` defined in it.

**Comment by danielgesua** [comment]
Bootstrap is locally installed and within the static folder.

I do not have project specific configurations for this project.

**Comment by ecmel** [comment]
Please put this file in `.vscode/settings.json` in your project folder:

```json
{
  "css.styleSheets": [
    "static/**/*.css"
  ]
}
```

If your style sheet files ends with a different extension use that one.
