### ISSUE TITLE
Install vscode plugin failed with http status 400

### ISSUE THREAD

**Issue by blade254353074** [ecmel/vscode-html-css#28]
```bash
$ code --install-extension vscode-html-css
Server returned 400
```

...Is that vscode's problem?

**Comment by blade254353074** [comment]
![image](https://cloud.githubusercontent.com/assets/9346008/25899776/b21191c8-35c3-11e7-928a-d8f4e82c181f.png)

**Comment by ecmel** [comment]
The following should work:

` code --install-extension ecmel.vscode-html-css `

**Comment by blade254353074** [comment]
![image](https://cloud.githubusercontent.com/assets/9346008/25904369/a3d364a2-35d1-11e7-9253-f78b153fa493.png)
...What's wrong with my vscode😢

**Comment by blade254353074** [comment]
Oh...I figured out.

`$ sudo chmod -R 755 ~/.vscode`
