### ISSUE TITLE
autocompletion not working

### ISSUE THREAD

**Issue by justingallant1988** [ecmel/vscode-html-css#280]
Greetings - There seems to be some type of bug occurring. I have downloaded the plugin, reloaded the window, but the auto completion for classes isnt working. Is there a known bug? And how might i resolve this?

**Comment by ecmel** [comment]
Hi, did you specify your css files in settings.json?

**Comment by justingallant1988** [comment]
Do i only need to specify my css file like this in my JSON? Once i add this, any classes created in my stylesheet will show in a dropwdown in my html? Will any classes created in my html also show in a dropdown in my stylesheet?

   "css.styleSheets": ["src/style.css"]

**Comment by ecmel** [comment]
In your project's folder create a file  `.vscode/settings.json` like below:

```json
{
  "css.styleSheets": [
    "src/style.css"
  ]
}
```

You can use glob patterns as well. In file CSS definitions will also be available in html.

Hope helps.

**Comment by justingallant1988** [comment]
Ok. Thank you, in now see classes showing up in my html. I'm a beginner and just for clarity...

1.) Upon installing the extension, I must specify the css file in the JSON. It does not auto detect anything?
2.) If I create a class from my html file, is that supposed to show up in a dropdown in my css file? OR do i need to create the class inside my css file FIRST, than i will see it?

I appreciate the help. I wish there was a more robust tutorial, i feel like i'm not getting the most use out its capabilities.

**Comment by ecmel** [comment]
It all depends on your project structure. If you want the extension to complete for all html files in all projects let say the css from src folder you should edit user extension settings and enter following:

```json
"css.styleSheets": ["src/**/*.css"]
```

This way you do not need to put a settings.json per workspace.

Hope helps.

**Comment by justingallant1988** [comment]
Ok got it. Thanks
