### ISSUE TITLE
Autocomplete not working for CSS or Bootstrap

### ISSUE THREAD

**Issue by jonathonpday** [ecmel/vscode-html-css#283]
Good Evening,

I am trying to use the extension as explained in previous answers here but for some reason the dropdown of suggested class attributes is not happening either for vanilla css or bootstrap, even after re-installing and restarting.

To be clear my `index.html` file looks like this:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" href="styles.css" />
    <title>Document</title>
  </head>
  <body>
    <div class=""></div>
  </body>
</html>
```

And my `settings.json` file contains the requested lines to add the css file and bootstrap:

```
  "css.enabledLanguages": ["html"],
  "css.styleSheets": [
    "node_modules/bootstrap/dist/css/bootstrap.css",
    "src/**/*.css"
  ]
}
```

I have added some test classes to my `styles.css` file but none are prepopulating in the html and nothing for bootstrap either.

I have tried to follow the other solutions here but so far no joy - is there anything I am missing with this?

**Comment by jonathonpday** [comment]
Also, have tried to downgrade to version 1.14.0 but the issue unfortunately persists.

**Comment by jonathonpday** [comment]
Ok, have now tried version 1.14.1 and it does appear to be working, but now multiple versions of the same attribute show on the dropdown:

<img width="616" alt="Screenshot 2024-01-27 at 16 40 57" src="https://github.com/ecmel/vscode-html-css/assets/36718060/a8328d06-52c3-47d5-86a7-f49aa3ca5939">

**Comment by ecmel** [comment]
If you are using cdn, you can try the following settings json as well:

```json
 "css.styleSheets": [
    "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css",
  ]
```

**Comment by jonathonpday** [comment]
Thank you!

It worked for the latest version which is great.

The only issue is the stylsheets did not work with the various paths, in the end the only way to get it to work was linking directly:

<img width="677" alt="Screenshot 2024-01-27 at 17 47 08" src="https://github.com/ecmel/vscode-html-css/assets/36718060/5ddeb4ad-8b40-42de-b0ad-accd3413e7da">

Is there a better way?

**Comment by ecmel** [comment]
Yes, for example the following will match all css and scss file under your project's src folder:

`"src/**/*.{css, scss}"`
