### ISSUE TITLE
Suggestions hide when typing a dash

### ISSUE THREAD

**Issue by TheColorRed** [ecmel/vscode-html-css#3]
When typing a `-`, the suggestion box closes.

![dash-hides-suggestions](https://cloud.githubusercontent.com/assets/1571806/16993049/71a28956-4e67-11e6-9312-c9994627b93f.gif)

**Comment by ecmel** [comment]
What is the version of Visual Studio Code? I can not reproduce the problem on 1.3.1

**Comment by ecmel** [comment]
It should be related to blade syntax files.

**Comment by ecmel** [comment]
Commit https://github.com/ecmel/vscode-html-css/commit/4bf7f671e33f611098ae65df2cabd9557950f9dd should fix it.
