### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Rhuaer** [ecmel/vscode-html-css#51]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|0.10.13
vscode-markdownlint|Dav|0.11.0
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
jquerysnippets|don|0.0.1
xml|Dot|1.9.2
gitlens|eam|6.0.0
vscode-html-css|ecm|0.1.8
git-project-manager|fel|1.4.0
auto-rename-tag|for|0.0.15
beautify|Hoo|1.1.1
vscode-fileheader|mik|0.0.2
HTMLHint|mka|0.4.0
python|ms-|0.8.0
azure-account|ms-|0.2.0
cpptools|ms-|0.14.2
csharp|ms-|1.13.0
debugger-for-chrome|msj|3.5.0
vscode-icons|rob|7.17.0
code-settings-sync|Sha|2.8.5
stylelint|shi|0.30.0
code-spell-checker|str|1.4.12
jsx|Twe|0.0.1

(1 theme extensions excluded)
---

Steps to Reproduce:

1. Install [dva-cli](https://github.com/dvajs/dva) and create a project with `dva new demoProject`,
2. Low cpu cost if I disable all extensions,
3. High cpu cost if I enable HTML CSS Support only.

Reproduces without extensions: No

**Comment by lolmaus** [comment]
Not only does the `code --type=extensionHost` process consume 100% of one CPU core, but it also keeps running after I exit Code.

If I start and quit Code several times, there will be several orphaned `code --type=extensionHost` processes left, each attempting to consume 100% CPU.

I've captured a screen recording as proof: https://youtu.be/Agz2S2mNpXI

On the video: 

1. I start Code with `vscode-html-css` disabled, then quit it and see that there are no orphaned processes left.
2. Start Code, enable `vscode-html-css`, reload, then exit. See that there's an orphaned processes with 100% CPU core load (shows as 25% of 4 cores).
3. Start and quit Code, see that there are two orphaned processes now!
4. Disable `vscode-html-css`, reload, quit, kill orpahed processes. Start Code with `vscode-html-css` disabled, quit and see that there are no orphaned processes left.

**Comment by Rhuaer** [comment]
@lolmaus 
Wish https://github.com/Microsoft/vscode/issues/35659 may help you.

**Comment by lolmaus** [comment]
@Rhuaer That's a really long thread, what specifically are you suggesting?

I've identified that my CPU consumption problem is related to this particular extension. I'd rather disable it than start hacking Code heavily to work around the extension's problem...

**Comment by Rhuaer** [comment]
@lolmaus 
Scroll the page to the end, and see the answer with many thumbs up.

**Comment by lolmaus** [comment]
@Rhuaer Setting `"search.followSymlinks": false` does not resolve the issue for me.

**Comment by Rhuaer** [comment]
@lolmaus 
Sorry to hear that.
In the end, I uninstall the extension, vscode-html-css. :)

**Comment by yoyo837** [comment]
Excuse me, why `wontfix` ?
