### ISSUE TITLE
Is possible to restrict suggestion only for HTML / CSS (without PHP context)

### ISSUE THREAD

**Issue by Kcko** [ecmel/vscode-html-css#57]
Hi @ecmel , 

Im using ur extension together with PHP intelisence, it make a little mess together.

Your extension should have limitation only for HTML / CSS context,  in PHP it should not live in PHP at all

See example: Im finding some internal methods in PHP
with your extension: https://goo.gl/dzGYpA (its wrong, its offer local variables etc, this has to be solved by PHP intelisence)
without your extension: https://goo.gl/2c1j7G  (explanation in previous point)

Thx for feedback.

PS. Im missing your answer at #55

**Comment by stefanomonteiro** [comment]
Same here. Can't find classes in Scss files

**Comment by dlucian85** [comment]
> 
> 
> Hi @ecmel ,
> 
> Im using ur extension together with PHP intelisence, it make a little mess together.
> 
> Your extension should have limitation only for HTML / CSS context, in PHP it should not live in PHP at all
> 
> See example: Im finding some internal methods in PHP
> with your extension: https://goo.gl/dzGYpA (its wrong, its offer local variables etc, this has to be solved by PHP intelisence)
> without your extension: https://goo.gl/2c1j7G (explanation in previous point)
> 
> Thx for feedback.
> 
> PS. Im missing your answer at #55
I was looking for the same option but looks like oficially there is no way of solving this issue, but i came of with a quick fix.
Just go to `C:\` >  `Users` > yourWindowsUser > `.vscode` > `extensions` > `ecmel.vscode-html-css-0.2.3` > `dist` and open `extension.js` file. You will see a minified version of the extension but just search for `const t=["html","django-html","laravel-blade` and remove your desired language from the array. Save it and reload VS Code. This worked for me. Hope this helps :)

**Comment by Kcko** [comment]
> > Hi @ecmel ,
> > Im using ur extension together with PHP intelisence, it make a little mess together.
> > Your extension should have limitation only for HTML / CSS context, in PHP it should not live in PHP at all
> > See example: Im finding some internal methods in PHP
> > with your extension: https://goo.gl/dzGYpA (its wrong, its offer local variables etc, this has to be solved by PHP intelisence)
> > without your extension: https://goo.gl/2c1j7G (explanation in previous point)
> > Thx for feedback.
> > PS. Im missing your answer at #55
> > I was looking for the same option but looks like oficially there is no way of solving this issue, but i came of with a quick fix.
> > Just go to `C:\` >  `Users` > yourWindowsUser > `.vscode` > `extensions` > `ecmel.vscode-html-css-0.2.3` > `dist` and open `extension.js` file. You will see a minified version of the extension but just search for `const t=["html","django-html","laravel-blade` and remove your desired language from the array. Save it and reload VS Code. This worked for me. Hope this helps :)

Thx for ur help. I dont want to use use buggy extension and this extension has died.
Now I´m using https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion which makes a much better results :-), try it too ;)
