### ISSUE TITLE
bug in .vue file

### ISSUE THREAD

**Issue by ZSkycat** [ecmel/vscode-html-css#62]
attribute `v-bind:class` and `:class` can work.
but `class` can not work.

Remark
- `class` attribute is static
- `v-bind:class` and `:class` attribute is reactivity

![20180803](https://user-images.githubusercontent.com/20368649/43601583-1a5025ca-96c0-11e8-852d-50987fd3f933.gif)

**Comment by willdante** [comment]
Same problem here on a fresh install.

**Comment by msacchetti** [comment]
Third

**Comment by jacksonyu** [comment]
same problem

**Comment by unomisa** [comment]
same problem

**Comment by aeadedoyin** [comment]
same problem

**Comment by msacchetti** [comment]
Happening again. Fresh install of VSCode and this extension on a MacBook pro, Chrome

**Comment by gowago** [comment]
i have the same problem in vue3
