### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by tolubydesign** [ecmel/vscode-html-css#66]
- Issue Type: `Performance`
- Extension Name: `vscode-html-css`
- Extension Version: `0.2.0`
- OS Version: `Linux x64 4.19.9-041909-generic`
- VSCode version: `1.30.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/tolulope/ecmel.vscode-html-css-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

Haven't reported an issue through GitHub for, apologies for that. Was checking the current programs that were running, through VS Code. Noticed that this program was not active. Started it from Host Profile.

**Comment by ecmel** [comment]
Duplicate https://github.com/ecmel/vscode-html-css/issues/51
