### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Mrooze-zeng** [ecmel/vscode-html-css#67]
- Issue Type: `Performance`
- Extension Name: `vscode-html-css`
- Extension Version: `0.2.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/mrooze/ecmel.vscode-html-css-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ecmel** [comment]
Duplicate https://github.com/ecmel/vscode-html-css/issues/51
