### ISSUE TITLE
CSS files in folders excluded with `files.exclude` do not get parsed

### ISSUE THREAD

**Issue by garyking** [ecmel/vscode-html-css#68]
I have `"**/node_modules": true` as one of my entries for VS Code's `files.exclude` settings. If this setting is enabled, then CSS files in the `node_modules` dir, such as from the `bootstrap` NPM package, won't get crawled by this extension.

I was able to test this by setting `"**/node_modules": false` in just one workspace, and then it was able to crawl Bootstrap classes.

Is it possible to get this extension to crawl `node_modules` files, even when it's excluded with `files.exclude`?

**Comment by maxiqboy** [comment]
oh my god, thanks @garyking  

I took one day to figure out what the h3ll my VScode cannot show autocomplete to CSS frameworks I had installed via NPM.

Thanks for your idea, now I finally got the answer
