### ISSUE TITLE
Html Zen Support

### ISSUE THREAD

**Issue by TheColorRed** [ecmel/vscode-html-css#7]
vscode supports zen coding:

```
div.my-class.my-other-class
```

Then when you press <kbd>Tab</kbd> when you are at the end of the line it creates this:

```
<div class="my-class my-other-class"></div>
```

It would be nice to have intellisense for this.

**Comment by ecmel** [comment]
Commit https://github.com/ecmel/vscode-html-css/commit/3dd6d7277c5b2e65601737f7951ac9c434b232ce should fix. Need to press Ctrl+Space for completion.
