### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by BillKG** [ecmel/vscode-html-css#70]
- Issue Type: `Performance`
- Extension Name: `vscode-html-css`
- Extension Version: `0.2.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.30.1`

[ecmel.vscode-html-css-unresponsive.cpuprofile.txt](https://github.com/ecmel/vscode-html-css/files/2709418/ecmel.vscode-html-css-unresponsive.cpuprofile.txt)

**Comment by ecmel** [comment]
Duplicate https://github.com/ecmel/vscode-html-css/issues/51
