### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by z3by** [ecmel/vscode-html-css#71]
- Issue Type: `Performance`
- Extension Name: `vscode-html-css`
- Extension Version: `0.2.0`
- OS Version: `Linux x64 4.15.0-43-generic`
- VSCode version: `1.30.1`

**Comment by SharakPL** [comment]
What's with those multiple issues? I didn't notice any high CPU or RAM consumption from this module and my pc config is almost 10 years old ;p

**Comment by ecmel** [comment]
Duplicate https://github.com/ecmel/vscode-html-css/issues/51
