### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by yspef** [ecmel/vscode-html-css#73]
- Issue Type: `Performance`
- Extension Name: `vscode-html-css`
- Extension Version: `0.2.0`
- OS Version: `Linux x64 4.9.0-8-amd64`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/facundo/ecmel.vscode-html-css-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ecmel** [comment]
Duplicate https://github.com/ecmel/vscode-html-css/issues/51
