### ISSUE TITLE
Replace text instead of append to it

### ISSUE THREAD

**Issue by TheColorRed** [ecmel/vscode-html-css#8]
When I have a class that I want to change, like this:

```html
<div class="text-left"></div>
```

I then delete the part I want to change like this:

```html
<div class="text-"></div>
```

Then type <kbd>R</kbd> to bring up intellisense, and select `text-right` from the list, and what happens is, that it just appends it to the current class instead of replacing it so it looks like this:

```html
<div class="text-text-right"></div>
```

What really should happen is that it replaces the current item completely so I get this:

```html
<div class="text-right"></div>
```

**Comment by ecmel** [comment]
Related upstream issue https://github.com/Microsoft/vscode/issues/10266

Seems it can be solved by providing a text edit to the completion item.

**Comment by ecmel** [comment]
Changed html word pattern with commit https://github.com/ecmel/vscode-html-css/commit/f712b1e01d796864525adb4116d809334565e553

Should be fixed.
