### ISSUE TITLE
Class suggestions don't show up after acceppting attribute autocompletion

### ISSUE THREAD

**Issue by franciscolourenco** [ecmel/vscode-html-css#92]
**Steps to reproduce**
1. Accept `class=""` completion
2. Start typing
3. **Auto completion doesn't show up (it should)**
4. Move the cursor outside the class attribute
5. Move the cursor inside the class attribute
6. Start typing
7. Auto completion works as expected

![2019-03-28 18 38 34](https://user-images.githubusercontent.com/208149/55180205-65b15280-5189-11e9-8a8b-1fd050e9016e.gif)

**Comment by lzf14250** [comment]
I happened the same problem, still waiting for bug fixing

**Comment by msacchetti** [comment]
Third
